config/routes.rb
Rails.application.routes.draw do
  get 'books/index'
  get 'books/show'
  get 'books/create'
  get 'books/new'
  get 'index/new'
  get 'index/show'
  get 'index/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  resources :authors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author

    def author_attributes=(attributes)
        self.author = Author.find_or_create_by(attributes)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
require 'byebug'
class BooksController < ApplicationController
  before_action :set_books, only: [:show, :edit, :update, :delete]
  def index
    @book = Book.all
  end

  def show
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def new
    @book = Book.new
    @book.author = Author.new
  end

  private

  def book_params
    params.require(:book).permit(:title, author_attributes: [:name])
  end

  def set_books
    unless @book = Book.find_by_id(params[:id])
    redirect_to books_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

<% @book.each do |book|%>
<li><%= link_to book.title, book_path(book)%></li>
<%end%>
<br>
<%=link_to "New Book", new_book_path%>

app/views/books/new.html.erb
<h1>Create New Book</h1>

<%= form_for @book do |f| %>
    <p>
	<%= f.label :title, "Title:" %>
	<%= f.text_field :title %>

    </p>
    <p>
	<%= f.fields_for :author do |ff| %>
	    <%= ff.label :name, "Author Name:" %>
	    <%= ff.text_field :name %>
	<% end %>
    </p>
    <p>
	<%= f.submit %>
    </p>
<% end %>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>
<h1>Book #<%=@book.id%></h1>
<h3>Title: <%=@book.title%><br>
Author: <%=@book.author.name%></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>